import os
import shutil

def generate_html_report():
    print("=== Starting report generation ===")

    with open('assets/accuracy.txt', 'r') as f:
        accuracy = f.read().strip()
    print(f"Loaded accuracy: {accuracy}")

    os.makedirs('docs', exist_ok=True)
    shutil.copy('assets/confusion_matrix.png', 'docs/confusion_matrix.png')
    print("Image copied to docs/")

    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>Iris Classifier Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background-color: #f5f5f5; }}
        .container {{ max-width: 800px; margin: auto; background: white; padding: 20px; border-radius: 10px; }}
        h1 {{ color: #2c3e50; }}
        .metric {{ font-size: 24px; color: #27ae60; font-weight: bold; }}
        img {{ max-width: 100%; margin: 20px 0; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Iris Classifier - Model Report</h1>
        <p>Accuracy: <span class="metric">{float(accuracy)*100:.1f}%</span></p>
        <h2>Confusion Matrix</h2>
        <img src="confusion_matrix.png" alt="Confusion Matrix">
        <p>Generated by CI/CD pipeline</p>
    </div>
</body>
</html>"""

    with open('docs/index.html', 'w') as f:
        f.write(html_content)
    print("✅ HTML report generated at docs/index.html")

if __name__ == "__main__":
    generate_html_report()